#!/usr/bin/env bash

# Stop nginx if it's already running
sudo service nginx stop

# Update nginx configuration
sudo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen .*/listen 8080;/g' /etc/nginx/conf.d/default.conf

# Start nginx
sudo service nginx start
